In [19]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [20]:
data = pd.read_csv('/content/emails.csv')
data.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [21]:
data.isnull().sum()

text    0
spam    0
dtype: int64

In [22]:
data.shape

(5728, 2)

In [23]:
x=data['text']
y=data['spam']

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)
print(x.shape,x_train.shape,x_test.shape)

(5728,) (4582,) (1146,)

In [25]:
n_value = TfidfVectorizer(min_df=1, stop_words='english', lowercase=True)
x_train_feature = n_value.fit_transform(x_train)
x_test_feature = n_value.transform(x_test)

In [28]:
model = LogisticRegression()
model.fit(x_train_feature, y_train)

LogisticRegression()

In [31]:
pridict_train = model.predict(x_train_feature)
accuracy_score(y_train,pridict_train)

0.9949803579223047

In [32]:
pridict_test = model.predict(x_test_feature)
accuracy_score(y_test,pridict_test)

0.9773123909249564

predictive system

In [43]:
input_mail = ["unbelievable new homes made easy  im wanting to show you this  homeowner  you have been pre - approved for a $ 454 , 169 home loan at a 3 . 72 fixed rate .  this offer is being extended to you unconditionally and your credit is in no way a factor .  to take advantage of this limited time opportunity  all we ask is that you visit our website and complete  the 1 minute post approval form  look foward to hearing from you ,  dorcas pittman"]
input_mail_feature = n_value.transform(input_mail)
prediction = model.predict(input_mail_feature)
print(prediction)
if prediction[0]== 1:
  print("spam")
else:
  print("not spam")

[1]
spam